import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { Trophy, ChevronDown, ChevronUp, Leaf, Award, Sparkles, RefreshCw } from 'lucide-react';
import { useMissions } from '../hooks/useMissions';
import { MissionCard } from './MissionCard';
import EcoPointsBadge from './EcoPointsBadge';
import { api } from '../lib/api';

interface MissionCenterProps {
  userId: string;
}

export const MissionCenter: React.FC<MissionCenterProps> = ({ userId }) => {
  const navigate = useNavigate();
  const [completedExpanded, setCompletedExpanded] = useState(false);

  const {
    pendingMissions,
    activeMissions,
    completedMissions,
    isLoading: isMissionsLoading,
    generateMissions,
    isGenerating,
    acceptMission,
    isAccepting,
    completeMission,
    isCompleting,
  } = useMissions(userId);

  // Fetch insights to verify if AI plan is available
  const { data: insights, isLoading: isInsightsLoading } = useQuery({
    queryKey: ['insights', userId],
    queryFn: () => api.agents.insights(userId),
    enabled: !!userId,
  });

  const isLoading = isMissionsLoading || isInsightsLoading;

  const hasAIPlan = !!insights?.planner;
  const isActionLoading = isGenerating || isAccepting || isCompleting;

  const handleGenerateMissions = async () => {
    if (!hasAIPlan) {
      navigate('/chat?analyze=true');
      return;
    }
    try {
      await generateMissions();
    } catch (err) {
      // handled by mutation
    }
  };

  if (isLoading) {
    return (
      <div className="space-y-6 animate-pulse">
        <div className="h-40 bg-slate-100 dark:bg-slate-900/40 rounded-2xl border border-slate-200 dark:border-slate-800"></div>
        <div className="space-y-3">
          <div className="h-6 w-32 bg-slate-200 dark:bg-slate-800 rounded-lg"></div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="h-44 bg-slate-100 dark:bg-slate-900/40 rounded-2xl border border-slate-200 dark:border-slate-800"></div>
            <div className="h-44 bg-slate-100 dark:bg-slate-900/40 rounded-2xl border border-slate-200 dark:border-slate-800"></div>
          </div>
        </div>
      </div>
    );
  }

  // Calculate stats
  const totalCompletedPoints = completedMissions.reduce((acc, curr) => acc + curr.eco_points_reward, 0);

  return (
    <div className="space-y-8">
      {/* Top Banner with Badging */}
      <EcoPointsBadge />

      <p className="text-xs text-slate-600 dark:text-slate-400 bg-white dark:bg-slate-900/40 border border-slate-200 dark:border-slate-800 shadow-sm dark:shadow-none px-4 py-3 rounded-xl leading-relaxed flex items-center gap-2">
        <Sparkles size={14} className="text-amber-500 dark:text-amber-400 shrink-0" />
        <span>Your missions are automatically generated by AI based on your actual carbon hotspots to maximize ecological offset.</span>
      </p>

      {/* Section 1: Active Challenges */}
      <div className="space-y-4">
        <h3 className="text-lg font-bold text-slate-800 dark:text-white flex items-center gap-2">
          <Trophy size={18} className="text-emerald-500 dark:text-emerald-400" />
          <span>Active Challenges</span>
          <span className="text-xs bg-emerald-100 dark:bg-emerald-500/20 text-emerald-600 dark:text-emerald-400 px-2 py-0.5 rounded-full font-semibold">
            {activeMissions.length}
          </span>
        </h3>

        {activeMissions.length === 0 ? (
          <div className="text-center py-8 rounded-2xl border border-dashed border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-900/20 text-slate-500 dark:text-slate-400">
            <p className="text-sm font-medium">No active challenges</p>
            <p className="text-xs text-slate-400 dark:text-slate-500 mt-1">Accept an available challenge below to start offsetting emissions.</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {activeMissions.map((m) => (
              <MissionCard
                key={m.id}
                mission={m}
                onComplete={completeMission}
                isActionLoading={isActionLoading}
              />
            ))}
          </div>
        )}
      </div>

      {/* Section 2: Available Challenges */}
      <div className="space-y-4">
        <div className="flex justify-between items-center">
          <h3 className="text-lg font-bold text-slate-800 dark:text-white flex items-center gap-2">
            <Award size={18} className="text-emerald-500 dark:text-emerald-400" />
            <span>Available Challenges</span>
            <span className="text-xs bg-slate-200 dark:bg-slate-800 text-slate-700 dark:text-slate-300 px-2 py-0.5 rounded-full font-semibold">
              {pendingMissions.length}
            </span>
          </h3>

          <button
            onClick={handleGenerateMissions}
            disabled={isActionLoading}
            className="flex items-center gap-1.5 px-3 py-1.5 bg-emerald-600/10 hover:bg-emerald-600/20 text-emerald-400 disabled:opacity-50 text-xs font-bold rounded-lg border border-emerald-500/20 transition-all"
          >
            {isGenerating ? <RefreshCw size={12} className="animate-spin" /> : <Leaf size={12} />}
            <span>{hasAIPlan ? 'Generate Challenges' : 'Analyze Footprint First'}</span>
          </button>
        </div>

        {pendingMissions.length === 0 ? (
          <div className="text-center py-10 rounded-2xl border border-dashed border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-900/20 text-slate-500 dark:text-slate-400 max-w-md mx-auto space-y-4">
            <p className="text-sm font-medium">No challenges available</p>
            {!hasAIPlan ? (
              <>
                <p className="text-xs text-slate-500 max-w-xs mx-auto leading-relaxed">
                  Complete your first AI analysis to generate personalized missions tailored to your footprint.
                </p>
                <button
                  onClick={() => navigate('/chat?analyze=true')}
                  className="px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold rounded-xl shadow-md transition-colors"
                >
                  Analyze with AI
                </button>
              </>
            ) : (
              <p className="text-xs text-slate-500 max-w-xs mx-auto">
                Tap the "Generate Challenges" button to generate fresh offsets based on your latest strategies.
              </p>
            )}
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {pendingMissions.map((m) => (
              <MissionCard
                key={m.id}
                mission={m}
                onAccept={acceptMission}
                isActionLoading={isActionLoading}
              />
            ))}
          </div>
        )}
      </div>

      {/* Section 3: Completed Challenges */}
      {completedMissions.length > 0 && (
        <div className="space-y-3 pt-4 border-t border-slate-200 dark:border-slate-800/60">
          <button
            onClick={() => setCompletedExpanded(!completedExpanded)}
            className="w-full flex items-center justify-between text-left text-slate-700 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white transition-colors"
          >
            <div className="flex items-center gap-2">
              <Trophy size={16} className="text-slate-500 dark:text-slate-400" />
              <span className="text-sm font-bold">Completed Challenges ({completedMissions.length})</span>
              <span className="text-[10px] px-2 py-0.5 bg-emerald-100 dark:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 rounded-full font-semibold border border-emerald-200 dark:border-emerald-500/10">
                +{totalCompletedPoints} pts earned
              </span>
            </div>
            {completedExpanded ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
          </button>

          {completedExpanded && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-2 animate-in fade-in duration-200">
              {completedMissions.map((m) => (
                <MissionCard key={m.id} mission={m} />
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
};
